name: Release

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout Repo
        uses: actions/checkout@v3

      - name: ⬢ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '*'
          cache: yarn

      - name: 🔑 Setup NPM
        run: |
          npm set "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}"

      - name: 📦 Install Packages
        run: yarn install --frozen-lockfile

      - name: ⚙️ Build Packages
        run: yarn build

      - name: 👤 Setup Identity
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

      - name: 🚀 Release
        run: yarn release --create-release github --conventional-graduate
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
